services:

 redis: 
  image: redis:7
  container_name: redis
  restart: always
  ports: 
  - "6379:6379"
#  backend: 
  # build: ./
  # container_name: backend
  # ports: 
  #  - "3000:3000"
  # depends_on: 
  #  - minIo
  #  - redis
  #  - postgres
  # environment: 
  #  PORT : 3000
  #  nodemailer_pass : njry tlkh carc dpbw
  #  table : users
  #  Management : management
  #  branch_table : branches
  #  cars_table : cars  
  #  booking_table : bookings
  #  jwt_key : 9392983478
  #  RazorpayAPIKey : rzp_test_STuA5rLGbi8xST 
  #  RazorpayKeySecret : 8F1lSZLsERQeFtpTW47Ev4an
